#spring:
#  batch:
#    job:
#      names: helloWorldJob
  datasource:
    url: "jdbc:h2:mem:test"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
